CREATE TABLE tbl_board (
	bno INT AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(500) NOT NULL,
	content VARCHAR(2000) NOT NULL,
	writer VARCHAR(50) NOT NULL,
	regdate TIMESTAMP DEFAULT NOW(),
	updatedate TIMESTAMP DEFAULT NOW(),
	delflag BOOLEAN DEFAULT FALSE
);


CREATE TABLE tbl_reply (
	rno INT AUTO_INCREMENT PRIMARY KEY,
	replyText VARCHAR(500) NOT NULL,
	replier VARCHAR(50) NOT NULL,
	regdate TIMESTAMP DEFAULT NOW(),
	updatedate TIMESTAMP DEFAULT NOW(),
	delflag BOOLEAN DEFAULT FALSE,
	bno INT NOT NULL
);


ALTER TABLE tbl_reply ADD CONSTRAINT fk_reply_board FOREIGN KEY (bno) REFERENCES tbl_board(bno);

CREATE INDEX idx_reply_board ON tbl_reply (bno DESC, rno ASC);

CREATE table tbl_product (
	pno INT AUTO_INCREMENT PRIMARY KEY,
	pname VARCHAR(200) NOT NULL,
	pdesc VARCHAR(1000) NOT NULL,
	price INT NOT NULL,
	sale BOOLEAN DEFAULT FALSE,
	writer VARCHAR(100) NOT NULL,
	regdate DATETIME DEFAULT CURRENT_TIMESTAMP,
	moddate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE table tbl_product_image (
	ino INT AUTO_INCREMENT PRIMARY KEY,
	pno INT NOT NULL,
	filename VARCHAR(300) NOT NULL,
	uuid CHAR(36) NOT NULL,
	ord INT DEFAULT 0,
	regdate DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (pno) REFERENCES tbl_product(pno) ON DELETE CASCADE
);


CREATE INDEX idx_product_image_pno ON tbl_product_image(pno, ino);

